name: post_clean_arc
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  bloc: ^8.0.3
  carousel_slider: ^4.0.0
  dio: ^4.0.6
  http: ^0.13.4
  dartz: ^0.10.1
  get_it: ^7.2.0
  internet_connection_checker: ^0.0.1+3
  flutter_screenutil: any
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  flutter_conditional_rendering: ^2.0.0
  fluttertoast: ^8.0.8
  hexcolor: ^2.0.5
  intl: ^0.17.0-nullsafety.2
  shared_preferences: ^2.0.15
  sizer: ^2.0.15
  smooth_page_indicator: ^1.0.0+2
  sqflite: ^2.0.0+4
  webview_flutter: ^2.0.14

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
